conda:
    file: doc/rtd_conda_environment.yml
build:
    image: latest
python:
    version: 3.6
    install:
        - requirements: docs/rtd_pip_environment.txt
        - method: pip
          path: .
    system_packages: true
formats:
    - htmlzip
