# Use this file to create a conda environment using:
# conda create -n <name> --file environment.yml

name: improver
channels:
  - conda-forge
dependencies:
  - python=3.6
  - iris=2.1
  - cf_units
  - python-stratify
