# This environment is a representative example for usage of IMPROVER
name: improver_a
channels:
  - conda-forge
  - main
dependencies:
  - python=3
  # Required
  - cartopy
  - cftime
  - cf-units
  - clize
  - dask
  - iris
  - netCDF4
  - numpy
  - pandas
  - pytz
  - scipy
  - sigtools
  - sphinx
  # Optional
  - fastparquet
  - statsmodels
  - numba
  - pygam
  - pysteps
  - python-stratify
  # Development
  - astroid
  - bandit
  - codacy-coverage
  - filelock
  - mock
  - mypy
  - pytest
  - pytest-cov
  - pytest-xdist
  - safety
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - threadpoolctl