# This environment is a representative example for usage of IMPROVER
# It does not include dependencies for the following IMPROVER CLIs:
# estimate-emos-coefficients, nowcast-accumulate, nowcast-extrapolate
# and nowcast-optical-flow-from-winds
# See doc/source/Dependencies.rst for more information
name: improver_b
channels:
  - conda-forge
dependencies:
  - python=3
  # Required
  - cartopy
  - cftime
  - cf-units
  - clize
  - dask
  - iris
  - netCDF4
  - numpy
  - pandas
  - pytz
  - scipy
  - sigtools
  - sphinx
  # Optional
  - lightgbm
  - numba
  - python-stratify
  - treelite
  # Development
  - astroid
  - bandit
  - filelock
  - mock
  - mypy
  - pytest
  - pytest-cov
  - pytest-xdist
  - safety
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - threadpoolctl
